### ISSUE TITLE
performAction to use Action-provided values

### ISSUE THREAD

**Issue by solsend2l** [JChapman202/super-siren#1]
Would it be permissible to do this with `Helper.performAction`:

`request.get(someUrl).then(request.Helper.performAction(someActionName)) // no data!`

where the [data](https://github.com/JChapman202/super-siren/blob/master/lib/SirenHelpers.js#L39) comes from the Action [fields](https://github.com/kevinswiber/siren#fields-1), if no data was passed in?

Perhaps even an `extends`, where the `data` overwrites any Action-provided default values.

**Comment by solsend2l** [comment]
So I guess it already does this, basically. But the `data` is optional now in PR #2. Take a look and let me know what you think.

**Comment by JChapman202** [comment]
Thank you!  Sorry for the late response on this one.  I have merged PR #2.
