### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ashic** [JChapman202/super-siren#10]
I just did 

```
npm install super-siren
...
let Siren = require('super-siren')
Siren.get("url")....
```
It tells me that Siren.get is not a function. I try new Siren(), and it says it's not a constructor. Am I missing something?

**Comment by kevinswiber** [comment]
Just took a brief look.  I think if you're not using EcmaScript Modules, you need to do something like:

```js
const Siren = require('super-siren').default;
Siren.get("https://....");
```

**Comment by JChapman202** [comment]
@kevinswiber you are correct.  I should update the documentation to mention this fact.  Thank you sir!

**Comment by ashic** [comment]
That was the issue. Thanks.
